source:
    type: local
config:
  main:
    serverid: '12345'
    super_username: 'root'
    super_password: 'password'
    master_username: 'root'
    master_password: 'password'
    mysqld_options:
      expire_logs_days: '7'
      key_buffer_size: '16M'
      max_allowed_packet: '16M'
      max_binlog_size: '256M'
      max_connections: '256'
      myisam_recover_options: 'BACKUP'
      query_cache_limit: '1M'
      query_cache_size: '64M'
      server_id: '1032'
      symbolic_links: '0'
      sync_binlog: '6'
      thread_cache_size: '8'
      thread_stack: '192K'
volumes:
  data:
    method: local
    options:
      path: /tmp/scs-test/data
  binlog:
    method: local
    options:
      path: /tmp/scs-test/binlog
  replaylog:
    method: local
    options:
      path: /tmp/scs-test/replaylog
