#!/bin/bash

set -e

chown -R scs:scs /mnt/binlog
chown -R scs:scs /mnt/replaylog
chown -R scs:scs /mnt/data
[[ -d /mnt/data/mysql ]] || /usr/bin/mysql_install_db --defaults-file=/etc/mysqld/mysqld.ini