#!/bin/bash

export HOME=/root

mysql --batch -e 'SHOW MASTER STATUS' --vertical | grep -v '^*' | sed -r 's/^\s+([^:]+): (.*)$/Master_\1: \2/'
mysql --batch -e 'SHOW SLAVE STATUS' --vertical | grep -v '^*' | sed -r 's/^\s+([^:]+): (.*)$/Slave_\1: \2/'
